# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nebaris
email: hola@kaplangabriel.com
description: PÃ¡gina dedica a ayudar a programadores
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nebaris.net" # the base hostname & protocol for your site
paginate: 2

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
